---
title: "2019_08"
output: html_document
---

# August 2019
## 08-09-2019
Heading

  - sub
    - sub
  
Learned basic Github/Gitkraken/Markdown/Bookdown elements
Still need to acccess the student package for github

__*Lab*__

  - 6 different marine media are now in 125 mL flasks in 60 mL quantities
    -A1F
    - Marine NZSG
    - Chitin (shrimp chitin used)
    - CGS (used tryptic soy broth)
    - ISP2 fresh bfe + c
    - TB (terrific broth)
    
  - streaked marine plates of 137A-25 // K1164(70) and 139B-15 // K1088(66)
  - waiting for response on strain 114E-7 // kineo
  
## 08-14-2019

  - restreaked K1164 onto marine plate and K1088 into flask into A1F media
  - streaked from cryovials onto A1F plates and left at 37 degrees C
    - 131A-2 // K1214
    - 118C-2 // K1174
    - 128A-46 // K1040
    
## 08-16-2019
  - 6 different marine media 2 flasks each
  - A1M and A1F plates made (1 sleeve each)
  - 6 different freshwater media dry ingredients for 500 mL
  - no growth in flask or plate
  
## 08-21-2019
  - 6 different freshwater media finished for 5 flasks
    - 200 mL leftover for each media was left on bench
    - some 60 mL flasks on Chase's bench (ran out of room)
  - no further growth on plates (the heating incubator was found turned off, was turned back on today)
  - a bit of growth observed in flask
  - took K1174 out of incubator into room temp
  - streaked from the K1088 flask onto A1F plate, placed in 37 incubator

## 08-23-2019
  - no new growth observed on agar plates
  - restreaked K1164, K1214, K1174, and K1040 onto respective agar plates 
    - M, F, M, F
    - waited for cryovials to melt longer
    - used parafilm
    - left K1174 on bench at room temp, others in 37 incubator
    - ones without the old code 
      - thawed completely, vortexed, pipetted 40 uL and streak with sterile loop
    
*separate note*

  - 24 well plates in the order of
    - TB, CGS, ISP2, NZSG, A1, Chitin
    - pink tape marks the top 
    
## 08-26-2019
  - K1174 grew at room temp on agar plate so now in A1M liquid media on shaker
    - will need to make more A1M liquid media most likely
  - pulled other strains (besides K1088) into room temp as well on bench
  - K1088 plate did not grow but left in 37 degree incubator
  
*Organizational Purposes*
cryovial --> agar plate --> liquid media flask --> agar plate for purification

| Agar 1 | Liquid Media | Agar 2 | Purified Strain |
| ------ | ------------ | ------ | --------------- |
| K1214  | K1174        | K1088  |                 |
| K1040  |              |        |                 |
| K1164  |              |        |                 |

Check this table may not be right

## 08-28-2019
  - 1088 --> restreaking onto 2nd plate from liquid M
  - 1040 --> dumping whole cryovial F
  - 1214 --> putting into liquid media from uniform F
  - 1164 --> Jeongho M
  - 1174 --> streaking onto 2nd plate from liquid M
  

| Agar 1    | Liquid Media | Agar 2    | Purified Strain |
| ------    | ------------ | ------    | --------------- |
|           | K1174 (M)    | K1088 (M) |                 |
|           | K1040 (F)    | K1174 (M) |                 |
| K1164 (M) | K1214 (F)    |           |                 |

## 09-09-2019

| Agar 1    | Liquid Media | Agar 2    | Purified Strain |
| ------    | ------------ | ------    | --------------- |
| K1088 (M) |              | K1040 (F) |                 |
|           |              | K1214 (F) |    K1174 (M)    |
| K1164 (M) |              |           |                 |
 

  - K1174 from 8-28 is pure
  - K1088 had two strains in it so restreaked from cryovial onto new agar plate (pipette with 50 uL)
  - K1164 will be donated by Jeongho
  
  
## 09-13-2019
  
    - K1214 looks pure 
    - K1040 grown on A1F liquid media (whole cryovial) did not grow on A1F agar plate or in the media 
      - sediment, freshwater, 128A-46,
    - K1088 into liquid media (M)

## 09-18-2019

  - K1088 from liquid media onto new marine agar plate (second agar plate)
  - K1040 flask--will take 5 mL from it into new A1F media flask
  - A1M and A1F 500mL each dry components on bench for Friday

###Plan for next time?
  - liquid component of A1 medias
  - grow purified strains in respective A1 media
  - innoculate the 6 diff media with same bacteria simultaneously
  - make controls of the 6 diff media --> take at most 5 mL of each media and put into sterile container
  
## 09-20-2019
  - A1M and A1F liquid media into 60 mL flasks
  - Status of stains
    - second agar plate for K1088 still growing, will check on Monday
    - K1174 looked purified so innoculated new A1M liquid media
    - K1214 unsure if purified so innoculated new A1F liquid media
      - will restreak onto agar plate from this media on Monday and then check for purity on Wednesday 

## 09-23-2019
  - K1040 liquid media flask --> streak onto A1F agar
  - streak K1214 onto A1F agar
  - K1088 purified on agar plate so innoculate new A1M liquid media flask
  - K1174 looks like it's growing in the liquid media flask... will innoculate into 6 diff media types on Wednesday
  - talked to Jeongho about K1164, has plate somewhere on his bench
    - grew well for him initially on A1M agar plate
    - had trouble, especially with contanimation, afterwards with growing in other media and using in bioassays 
      - A1m + Na Butylate
      - ISP2
      - modified ISP2 (Glc-->Glycerol)
      - Defined media
      - NZSG

## 09-25-2019
  - K1040 into liquid A1F flask
  - K1164 1 mL of Sofia's cryovial placed into A1M liquid flask
  - dry components of media for NZSG, ISP2 bfe+c, and TB were made for marine 500 mL because the autoclaves were down
    - different colored liquid media for the flasks that were already made so to be sure, completely new flasks were made
    
## 09-27-2019
  - 8x 60 mL liquid media flasks made for the media types listed above
  - K1040 onto A1F agar
  - K1164 onto A1M agar 
    - may have to restreak on Monday from liquid bc not too much growth in liquid flask

## 09-30-2019

Where we are right now

  - K1174 A1M 9/20 PURIFIED LIQUID
  - K1088 A1M 9/23 PURIFIED LIQUID
  - K1040 A1F 9/27 AGAR NEEDS BE CHECKED FOR PURIFICATION (THEN INTO FINAL LIQUID)
  - K1164 A1M 9/27 AGAR NEEDS TO BE STREAKED ONTO LIQUID MEDIA FOR PURIFICATION PROCESS (THEN ONTO SECOND AGAR)
  - K1214 A1F 9/20 LAST FLASK... 9/9 SUPPOSEDLY PURE... GIVING UP?

## 10-02-2019
  - K1174 (A1M), K1088 (A1M), and K1040 (A1F) were innoculated into 6 different media types respective to what they were grown in
  - K1164 (A1M) onto second agar
  
## 10-04-2019
  - K1164 into A1m purification liquid media

## 10-07-2019
  K1164 was innoculated into 6 different media types. However, at the end of innoculation, it was noted that there were concerning orange clumps on the inside walls of the flask containing K1164 liquid media from 10/4... so new liquid media flask A1M was innoculated for K1164 using the agar plate from 10/2/2019. (should check that there is growth in both flasks next time you come into lab for the liquid medias) The agar plate shows dry looking, stringed whitish bacteria. The flasks were placed on the shaker. 
  
## 10-09-2019
  The hood was full so had to wait on the MALDI plates. Read up on IDBac using Jove. Installed IDBac.
  
## 10-11-2019
  MALDI is down :( 
  The bacteria (K1088, K1174, K1040) in 6 diff media types was moved into the bottom shelf of the -80 fridge off of the shaker because we wanted to slow everything down without killing the bacteria. Possible lysing may occur. K1164 was checked. Growth present in both flasks. "K1164 from plate" flask also had orange solid dot on the side of the flask, so we restreaked a new A1M flask with K1164 from the plate from 10/2/2019. The plate looks clean. 
  two versions of CGS liquid media (500 mL) was made in large culture flasks. New CGS contained new casamino and soytone components whereas the old CGS contained old components. This was because old CGS was observed to be growing a bacteria. 
  4 x 60 mL A1M media flasks were also made. 

## 10-16-2019
  MALDI plates using the JOVE protocol
  Allocated CHCA into 1 mL distributions into 5 microcentrifuge tubes
  matrix solution: 100 킠 solution = 50 킠 ACN + 47.5 킠 H2O + 2.5 킠 TFA + 1 mg CHCA
  The flasks containing the bacteria in the fridge were taken out of the fridge and were thawed in 35 degree water incubator. The MALDI plate was cleaned using a Kimwipe and methanol. 1 킠 of matrix solution was placed onto target spot on plate. 1 킠 of bacteria sample was taken from the flask and placed on top of the matrix solution. The two were mixed on the spot on the plate by pipetting up and down a few times.
  

#### 1174
  - C2-A1M
  - C3-ISP2 bfe + c
  - C4-CGS
  - D2-CHITIN
  - D3-LEFT FOR CALIBRATION
  - D4-NZSG
  - E3-TB
  
  
#### 1088
  - C15-A1M
  - C16-ISP2 bfe + c
  - C17-CGS
  - D15-CHITIN
  - D17-NZSG
  - E16-TB
  
  
#### 1040 
  - C9-A1F
  - C10-ISP2 bfe + c
  - C11-CGS
  - D9-CHITIN
  - D10-LEFT FOR CALIBRATION 
  - D11-NZSG
  - E10-TB
  
